version: '3.5'

services:
  memcached:
    image: memcached:alpine
    networks:
      - default
  mongo:
    image: mongo
    networks:
      - default
    volumes:
      - ./data/db:/data/db
      - .:/var/saseul-origin
  node:
    image: saseul-origin
    command: bin/start_node.sh
    networks:
      - default
    links:
      - memcached
      - mongo
    volumes:
      - .:/var/saseul-origin
      - ./logs:/var/log/saseul-origin
    env_file: .env
  api:
    image: saseul-origin
    networks:
      - default
    links:
      - memcached
      - mongo
    volumes:
      - .:/var/saseul-origin
      - ./logs:/var/log/saseul-origin
    env_file: .env
  web:
    image: nginx:alpine
    networks:
      - default
    links:
      - api
    ports:
      - 18080:80
    volumes:
      - .:/var/saseul-origin
      - ./api/nginx/site.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: saseul-origin
