#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

const ROOT_DIR = __DIR__;

$SASEUL_GID = getmygid();
$SASEUL_UID = getmyuid();

posix_setgid($SASEUL_GID);
posix_setuid($SASEUL_UID);

# Set Daemon
$manager = new \src\Manager();
$manager->Main();
